// Automatically generated by MockGen. DO NOT EDIT!
// Source: eventforwarder/eventforwarder.go

package mock_eventforwarder

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of EventForwarder interface
type MockEventForwarder struct {
	ctrl     *gomock.Controller
	recorder *_MockEventForwarderRecorder
}

// Recorder for MockEventForwarder (not exported)
type _MockEventForwarderRecorder struct {
	mock *MockEventForwarder
}

func NewMockEventForwarder(ctrl *gomock.Controller) *MockEventForwarder {
	mock := &MockEventForwarder{ctrl: ctrl}
	mock.recorder = &_MockEventForwarderRecorder{mock}
	return mock
}

func (_m *MockEventForwarder) EXPECT() *_MockEventForwarderRecorder {
	return _m.recorder
}

func (_m *MockEventForwarder) Forward(event string, infos map[string]interface{}) (int32, string, error) {
	ret := _m.ctrl.Call(_m, "Forward", event, infos)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (_mr *_MockEventForwarderRecorder) Forward(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Forward", arg0, arg1)
}
