version: "2"
run:
  timeout: 5m
  build-tags:
    - unit
    - integration
    - wireinject

linters:
  exclusions:
    paths:
    - "mock"
    - "_gen.go$"
    - "pb.go$"
    - "pb.gw.go$"
  enable:
    - goimports
