// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/topfreegames/maestro/internal/handlers"
	"github.com/topfreegames/maestro/internal/service"
)

// Injectors from wire.go:

func initializeManagementMux(ctx context.Context) (*runtime.ServeMux, error) {
	pingHandler := handlers.ProvidePingHandler()
	serveMux := service.ProvideManagementMux(ctx, pingHandler)
	return serveMux, nil
}
