// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"net/http"

	"github.com/topfreegames/maestro/internal/config"
)

// Injectors from wire.go:

func initializeHandlers(c config.Config) (map[string]http.Handler, error) {
	v := ProvideHandlers()
	return v, nil
}

// wire.go:

type Handlers = map[string]http.Handler

func ProvideHandlers() Handlers {
	return Handlers{}
}
