// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/core/ports/forwarder_grpc.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	forwarder "github.com/topfreegames/maestro/internal/core/entities/forwarder"
	eventforwarder "github.com/topfreegames/protos/maestro/grpc/generated"
	grpc "google.golang.org/grpc"
)

// MockForwarderGrpc is a mock of ForwarderGrpc interface.
type MockForwarderGrpc struct {
	ctrl     *gomock.Controller
	recorder *MockForwarderGrpcMockRecorder
}

// MockForwarderGrpcMockRecorder is the mock recorder for MockForwarderGrpc.
type MockForwarderGrpcMockRecorder struct {
	mock *MockForwarderGrpc
}

// NewMockForwarderGrpc creates a new mock instance.
func NewMockForwarderGrpc(ctrl *gomock.Controller) *MockForwarderGrpc {
	mock := &MockForwarderGrpc{ctrl: ctrl}
	mock.recorder = &MockForwarderGrpcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForwarderGrpc) EXPECT() *MockForwarderGrpcMockRecorder {
	return m.recorder
}

// CacheDelete mocks base method.
func (m *MockForwarderGrpc) CacheDelete(forwarderAddress string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CacheDelete", forwarderAddress)
	ret0, _ := ret[0].(error)
	return ret0
}

// CacheDelete indicates an expected call of CacheDelete.
func (mr *MockForwarderGrpcMockRecorder) CacheDelete(forwarderAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheDelete", reflect.TypeOf((*MockForwarderGrpc)(nil).CacheDelete), forwarderAddress)
}

// CacheFlush mocks base method.
func (m *MockForwarderGrpc) CacheFlush() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CacheFlush")
}

// CacheFlush indicates an expected call of CacheFlush.
func (mr *MockForwarderGrpcMockRecorder) CacheFlush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheFlush", reflect.TypeOf((*MockForwarderGrpc)(nil).CacheFlush))
}

// SendPlayerEvent mocks base method.
func (m *MockForwarderGrpc) SendPlayerEvent(ctx context.Context, forwarder forwarder.Forwarder, in *eventforwarder.PlayerEvent, opts ...grpc.CallOption) (*eventforwarder.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, forwarder, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendPlayerEvent", varargs...)
	ret0, _ := ret[0].(*eventforwarder.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendPlayerEvent indicates an expected call of SendPlayerEvent.
func (mr *MockForwarderGrpcMockRecorder) SendPlayerEvent(ctx, forwarder, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, forwarder, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPlayerEvent", reflect.TypeOf((*MockForwarderGrpc)(nil).SendPlayerEvent), varargs...)
}

// SendRoomEvent mocks base method.
func (m *MockForwarderGrpc) SendRoomEvent(ctx context.Context, forwarder forwarder.Forwarder, in *eventforwarder.RoomEvent, opts ...grpc.CallOption) (*eventforwarder.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, forwarder, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendRoomEvent", varargs...)
	ret0, _ := ret[0].(*eventforwarder.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendRoomEvent indicates an expected call of SendRoomEvent.
func (mr *MockForwarderGrpcMockRecorder) SendRoomEvent(ctx, forwarder, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, forwarder, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRoomEvent", reflect.TypeOf((*MockForwarderGrpc)(nil).SendRoomEvent), varargs...)
}

// SendRoomReSync mocks base method.
func (m *MockForwarderGrpc) SendRoomReSync(ctx context.Context, forwarder forwarder.Forwarder, in *eventforwarder.RoomStatus, opts ...grpc.CallOption) (*eventforwarder.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, forwarder, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendRoomReSync", varargs...)
	ret0, _ := ret[0].(*eventforwarder.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendRoomReSync indicates an expected call of SendRoomReSync.
func (mr *MockForwarderGrpcMockRecorder) SendRoomReSync(ctx, forwarder, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, forwarder, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRoomReSync", reflect.TypeOf((*MockForwarderGrpc)(nil).SendRoomReSync), varargs...)
}
