---
name: scheduler-with-metrics-and-legacy-trigger
game: game-name
image: maestro-dev-room:latest
imagePullPolicy: Never
occupiedTimeout: 3600
ports:
- containerPort: 8080
  protocol: TCP
  name: tcp
shutdownTimeout: 10
env:
- name: MAESTRO_HOST_PORT
  value: 192.168.64.1:8080
  valueFrom:
    secretKeyRef:
      name: ""
      key: ""
- name: POLLING_INTERVAL_IN_SECONDS
  value: "20"
  valueFrom:
    secretKeyRef:
      name: ""
      key: ""
autoscaling:
  min: 2
  max: 10
  up:
    delta: 1
    trigger:
      usage: 70
      time: 10
    metricsTrigger:
    - type: room
      usage: 50
      time: 10
    cooldown: 30
  down:
    delta: 1
    trigger:
      usage: 30
      time: 10
    cooldown: 60
