apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: maestro
spec:
  serviceName: "postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:17.1-alpine
        env:
        - name: POSTGRES_DB
          value: "maestro"
        - name: POSTGRES_USER
          value: "maestro"
        - name: POSTGRES_PASSWORD
          value: "maestro"
          livenessProbe:
            exec:
              command:
              - pg_isready
              - -U
              - maestro
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
              - pg_isready
              - -U
              - maestro
            initialDelaySeconds: 5
            periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  name: postgresql
  namespace: maestro
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresql
  clusterIP: None