apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: roomschedulers.maestro.io
spec:
  group: maestro.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - name
            - game
            - spec
            properties:
              name:
                type: string
              game:
                type: string
              state:
                type: string
                enum: ["creating", "terminating", "in-sync", "on-error"]
                default: "creating"
              spec:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              portRange:
                type: object
                properties:
                  start:
                    type: integer
                  end:
                    type: integer
              maxSurge:
                type: string
              roomsReplicas:
                type: integer
                minimum: 0
              forwarders:
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              autoscaling:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              annotations:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              labels:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              matchAllocation:
                type: object
                properties:
                  maxMatches:
                    type: integer
                    minimum: 1
              previousVersion:
                type: object
                description: "Stores the n-1 version for rollback"
                x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            properties:
              state:
                type: string
              stateLastChangedAt:
                type: string
                format: date-time
              lastScaleOpAt:
                type: string
                format: date-time
              lastDownscaleAt:
                type: string
                format: date-time
              createdAt:
                type: string
                format: date-time
              updatedAt:
                type: string
                format: date-time
  scope: Namespaced
  names:
    plural: roomschedulers
    singular: roomscheduler
    kind: RoomScheduler
    shortNames:
    - rs