// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/core/ports/forwarder/events_forwarder.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	events "github.com/topfreegames/maestro/internal/core/entities/events"
	forwarder "github.com/topfreegames/maestro/internal/core/entities/forwarder"
)

// MockEventsForwarder is a mock of EventsForwarder interface.
type MockEventsForwarder struct {
	ctrl     *gomock.Controller
	recorder *MockEventsForwarderMockRecorder
}

// MockEventsForwarderMockRecorder is the mock recorder for MockEventsForwarder.
type MockEventsForwarderMockRecorder struct {
	mock *MockEventsForwarder
}

// NewMockEventsForwarder creates a new mock instance.
func NewMockEventsForwarder(ctrl *gomock.Controller) *MockEventsForwarder {
	mock := &MockEventsForwarder{ctrl: ctrl}
	mock.recorder = &MockEventsForwarderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventsForwarder) EXPECT() *MockEventsForwarderMockRecorder {
	return m.recorder
}

// ForwardPlayerEvent mocks base method.
func (m *MockEventsForwarder) ForwardPlayerEvent(ctx context.Context, eventAttributes events.PlayerEventAttributes, forwarder forwarder.Forwarder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForwardPlayerEvent", ctx, eventAttributes, forwarder)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForwardPlayerEvent indicates an expected call of ForwardPlayerEvent.
func (mr *MockEventsForwarderMockRecorder) ForwardPlayerEvent(ctx, eventAttributes, forwarder interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForwardPlayerEvent", reflect.TypeOf((*MockEventsForwarder)(nil).ForwardPlayerEvent), ctx, eventAttributes, forwarder)
}

// ForwardRoomEvent mocks base method.
func (m *MockEventsForwarder) ForwardRoomEvent(ctx context.Context, eventAttributes events.RoomEventAttributes, forwarder forwarder.Forwarder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForwardRoomEvent", ctx, eventAttributes, forwarder)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForwardRoomEvent indicates an expected call of ForwardRoomEvent.
func (mr *MockEventsForwarderMockRecorder) ForwardRoomEvent(ctx, eventAttributes, forwarder interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForwardRoomEvent", reflect.TypeOf((*MockEventsForwarder)(nil).ForwardRoomEvent), ctx, eventAttributes, forwarder)
}

// Name mocks base method.
func (m *MockEventsForwarder) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockEventsForwarderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockEventsForwarder)(nil).Name))
}
